/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Dashboards {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  ownerId: string;
  updatedAt: Generated<Timestamp>;
}

export interface DashboardWidgetLayouts {
  breakpoint: string | null;
  breakpointSortOrder: number | null;
  dashboardId: string | null;
  h: number | null;
  w: number | null;
  widgetInstanceId: string | null;
  x: number | null;
  y: number | null;
}

export interface DashboardWidgets {
  config: Json | null;
  dashboardId: string | null;
  id: string | null;
  locked: boolean | null;
  schemaVersion: number | null;
  typeDisplayName: string | null;
  typeEnabled: boolean | null;
  typeEntryUrl: string | null;
  typeMinH: number | null;
  typeMinW: number | null;
  typeVersion: string | null;
  widgetType: string | null;
}

export interface Files {
  /**
   * NULL means not applicable - the file is not sequence-shaped, so the question
   *    does not arise. That is a different statement from the value 'not_sequence',
   *    which means the question was asked of something that turned out not to be a
   *    sequence, and both differ from 'ambiguous', which means asked and unresolved.
   */
  alphabet: string | null;
  /**
   * From the shared rule in tools/porttypes.json, implemented twice - by
   *    tools/runner/alphabet.py and web/src/server/tools/detect.ts - and held to one
   *    behaviour by the corpus at tools/corpus/alphabet.
   */
  alphabetConfidence: string | null;
  blobKey: string;
  byteSize: Int8;
  contentHash: string;
  createdAt: Generated<Timestamp>;
  detection: string | null;
  nodeId: string;
  portFormat: string | null;
  /**
   * Port type detected on upload, or NULL when nothing in the vocabulary matched.
   *    Format is meaningless without it, so the two are set and cleared together.
   */
  portType: string | null;
}

export interface GridBreakpoints {
  cols: number;
  minWidth: number;
  name: string;
  sortOrder: number;
}

export interface Nodes {
  /**
   * BlockNote document for an experiment: the editor's own block array. Empty for folders.
   */
  content: Generated<Json>;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  name: string;
  ownerId: string;
  parentId: string | null;
  position: Generated<number>;
  updatedAt: Generated<Timestamp>;
}

export interface SchemaMigrations {
  appliedAt: Generated<Timestamp>;
  version: string;
}

export interface Surfaces {
  displayName: string;
  name: string;
}

export interface TreeFiles {
  alphabet: string | null;
  alphabetConfidence: string | null;
  blobKey: string | null;
  byteSize: Int8 | null;
  contentHash: string | null;
  createdAt: Timestamp | null;
  detection: string | null;
  id: string | null;
  name: string | null;
  ownerId: string | null;
  parentId: string | null;
  portFormat: string | null;
  portType: string | null;
  position: number | null;
  updatedAt: Timestamp | null;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  displayName: string | null;
  email: string;
  id: Generated<string>;
}

export interface WidgetInstances {
  config: Generated<Json>;
  createdAt: Generated<Timestamp>;
  dashboardId: string;
  id: Generated<string>;
  /**
   * Pinned in place: not draggable or resizable, and other widgets compact around it.
   */
  locked: Generated<boolean>;
  schemaVersion: Generated<number>;
  updatedAt: Generated<Timestamp>;
  widgetType: string;
}

export interface WidgetLayouts {
  breakpoint: string;
  h: number;
  updatedAt: Generated<Timestamp>;
  w: number;
  widgetInstanceId: string;
  x: number;
  y: number;
}

export interface WidgetTypes {
  configSchema: Json;
  createdAt: Generated<Timestamp>;
  defaultH: Generated<number>;
  defaultW: Generated<number>;
  description: string | null;
  displayName: string;
  enabled: Generated<boolean>;
  entryUrl: string | null;
  minH: Generated<number>;
  minW: Generated<number>;
  surfaces: Generated<string[]>;
  type: string;
  version: string;
}

export interface DB {
  dashboards: Dashboards;
  dashboardWidgetLayouts: DashboardWidgetLayouts;
  dashboardWidgets: DashboardWidgets;
  files: Files;
  gridBreakpoints: GridBreakpoints;
  nodes: Nodes;
  schemaMigrations: SchemaMigrations;
  surfaces: Surfaces;
  treeFiles: TreeFiles;
  users: Users;
  widgetInstances: WidgetInstances;
  widgetLayouts: WidgetLayouts;
  widgetTypes: WidgetTypes;
}
