// GENERATED by scripts/generate-outcomes.mjs from tools/outcomes.json.
// Do not edit. Run `pnpm outcomes:types` after changing that file.
//
// Vocabulary version "1.0".

/** What a run of a wrapped tool ended as. */
export type ToolOutcome = "ok" | "nonzero_exit" | "timeout" | "oom" | "precondition_failed" | "missing_output" | "type_mismatch" | "image_missing";

/** What a run of the adapter agent ended as. None of these means "ready". */
export type AgentOutcome = "conformant" | "needs_review" | "gave_up" | "rejected";

/**
 * What a person does next. Outcomes are grouped by this rather than by what went
 * wrong: `precondition_failed` and `oom` are both "no result", but one is fixed
 * by choosing a different file and the other by us, and telling someone to wait
 * when they are one dropdown from done is worse than not grouping at all.
 */
export type OutcomeAction = "nothing" | "choose a different file" | "look at the data, or the tool" | "nothing; we fix it";

/** Rendering order. A list, not a set — "we fix it" must not sort above "choose a different file". */
export const ACTION_ORDER: readonly OutcomeAction[] = [
  "nothing",
  "choose a different file",
  "look at the data, or the tool",
  "nothing; we fix it",
];

/**
 * Every tool outcome with its description and action.
 *
 * Typed as a total `Record`, so an outcome added to outcomes.json without being
 * handled here fails to compile — and an outcome whose action is not in
 * ACTION_ORDER fails too, because OutcomeAction is built from that list alone.
 */
export const TOOL_OUTCOMES: Record<ToolOutcome, { description: string; action: OutcomeAction }> = {
  "ok": { description: "declared outputs exist, are non-empty, and detect as the declared type", action: "nothing" },
  "nonzero_exit": { description: "the tool reported failure honestly", action: "look at the data, or the tool" },
  "timeout": { description: "exceeded the declared budget", action: "nothing; we fix it" },
  "oom": { description: "killed against the machine class memory cap", action: "nothing; we fix it" },
  "precondition_failed": { description: "an input did not satisfy what the operation requires, so it never ran - the wrong kind of file, not a tool or platform failure", action: "choose a different file" },
  "missing_output": { description: "a declared output is absent or empty, whatever the exit code", action: "look at the data, or the tool" },
  "type_mismatch": { description: "an output exists but is not the declared type", action: "nothing; we fix it" },
  "image_missing": { description: "the image could not be obtained - infrastructure, not the tool", action: "nothing; we fix it" },
};

export const AGENT_OUTCOMES: Record<AgentOutcome, { description: string }> = {
  "conformant": { description: "adapter drafted and passing conform.py, ready for review" },
  "needs_review": { description: "conformant, but with a caveat a human should see - unknown license, or a port that fell back to the Text escape hatch" },
  "gave_up": { description: "could not produce a conformant adapter; the report says what it could not determine. The honest outcome, and far better than a plausible adapter nobody can trust" },
  "rejected": { description: "the run touched files outside its own adapter directory and was discarded. A guardrail trip, not a tool problem" },
};

/**
 * Numbers a `timeout` carries, because it is the one outcome whose correct
 * action genuinely depends on the run. "180s budget, 182s elapsed, input 58x the
 * fixture" tells a person which case they are in even inside a coarse bucket.
 */
export const TIMEOUT_EVIDENCE = [
  "budget_seconds",
  "elapsed_seconds",
  "input_bytes",
  "fixture_bytes",
  "input_vs_fixture",
] as const;

/** Outcomes that share an action, in rendering order. Empty groups are kept: a
 *  family with no runs is a fact, and dropping it makes the page change shape. */
export function groupByAction(
  counts: Partial<Record<ToolOutcome, number>>,
): { action: OutcomeAction; outcomes: { outcome: ToolOutcome; count: number }[]; total: number }[] {
  return ACTION_ORDER.map((action) => {
    const outcomes = (Object.keys(TOOL_OUTCOMES) as ToolOutcome[])
      .filter((outcome) => TOOL_OUTCOMES[outcome].action === action)
      .map((outcome) => ({ outcome, count: counts[outcome] ?? 0 }));
    return { action, outcomes, total: outcomes.reduce((sum, o) => sum + o.count, 0) };
  });
}
